const DEFAULT_FOOD=['火锅','烧烤','炒饭','面','汉堡','炸鸡','日料','麻辣烫'];
const FOOD_ICONS=[['汉堡','🍔'],['炸鸡','🍗'],['日料','🍣'],['火锅','🍲'],['面','🍜'],['拉面','🍜'],['披萨','🍕'],['米饭','🍚'],['炒饭','🍚'],['烧烤','🍢'],['麻辣烫','🍲']];
const state={food:JSON.parse(localStorage.getItem('pickone-food')||'null')||DEFAULT_FOOD,decide:[],excluded:null,history:JSON.parse(localStorage.getItem('pickone-history')||'[]')};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function randomIndex(max){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max}
function save(){localStorage.setItem('pickone-food',JSON.stringify(state.food));localStorage.setItem('pickone-history',JSON.stringify(state.history))}
function foodIcon(name){const found=FOOD_ICONS.find(([key])=>name.includes(key));return found?found[1]:'🍽️'}
function renderChips(type){const el=$(`#${type}-options`);el.innerHTML='';state[type].forEach((item,i)=>{const chip=document.createElement('div');chip.className='chip';chip.innerHTML=`<span>${item}</span><button class="chip-remove" aria-label="删除${item}">×</button>`;chip.addEventListener('click',e=>{if(e.target.matches('button')){state[type].splice(i,1);save();renderChips(type)}else{chip.classList.toggle('off');chip.dataset.off=chip.classList.contains('off')}});el.append(chip)});updateButtons()}
function updateButtons(){const food=$('[data-view="food"] .decide-action'),decide=$('[data-view="decide"] .decide-action');if(food)food.disabled=$$('#food-options .chip:not(.off)').length<2;if(decide)decide.disabled=$$('#decide-options .chip:not(.off)').length<2}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$('.back-button').hidden=name==='home';$('.history-drawer').hidden=true;state.excluded=null;if(name==='food')renderChips('food');if(name==='decide')renderChips('decide')}
function add(type,input){const value=input.value.trim();if(value&&!state[type].includes(value)){state[type].push(value);input.value='';save();renderChips(type)}}
function makeParticles(panel){const layer=document.createElement('div');layer.className='result-particles';for(let i=0;i<12;i++){const p=document.createElement('i'),angle=Math.PI*2*i/12+randomIndex(30)/100,distance=40+randomIndex(35);p.style.setProperty('--x',`${Math.cos(angle)*distance}px`);p.style.setProperty('--y',`${Math.sin(angle)*distance}px`);p.style.setProperty('--delay',`${randomIndex(12)/100}s`);layer.append(p)}panel.append(layer);setTimeout(()=>layer.remove(),1000)}
function animateResult(node,items,final,type){const end=performance.now()+1450;const tick=now=>{if(now<end){const item=items[randomIndex(items.length)];node.textContent=(type==='food'?foodIcon(item)+' ':'')+item;requestAnimationFrame(tick)}else{node.textContent=(type==='food'?foodIcon(final)+' ':'')+final;const panel=node.closest('.result-panel');panel.classList.add('locked');makeParticles(panel);if(navigator.vibrate)navigator.vibrate(12)}};requestAnimationFrame(tick)}
function pick(type){const view=$(`[data-view="${type}"]`),result=view.querySelector('.result-panel');const chips=[...view.querySelectorAll('.chip:not(.off)')].map(x=>x.firstElementChild.textContent).filter(x=>x!==state.excluded);if(chips.length<2)return;const final=chips[randomIndex(chips.length)];result.className='result-panel show';result.innerHTML='<div class="result-glow"></div><div class="result-label">结果是</div><div class="result-value"></div><div class="result-actions"><button class="keep">就它了</button><button class="again">再来一次</button><button class="exclude">排除这个结果</button></div>';animateResult(result.querySelector('.result-value'),chips,final,type);bindResultActions(result,type,final)}
function bindResultActions(panel,type,final){panel.querySelector('.keep').onclick=()=>confirmResult(panel,type,final);panel.querySelector('.again').onclick=()=>pick(type);panel.querySelector('.exclude').onclick=()=>{state.excluded=final;pick(type)}}
function confirmResult(panel,type,value){const button=panel.querySelector('.keep');button.classList.add('confirmed');button.textContent='✓ 就它了';panel.classList.add('accepted');record(type,value);showToast(`决定好了：${type==='food'?foodIcon(value)+' ':''}${value}`)}
function pickNumber(){const min=Math.ceil(Number($('#min-number').value)),max=Math.floor(Number($('#max-number').value));if(!Number.isFinite(min)||!Number.isFinite(max)||max<min)return;const final=min+randomIndex(max-min+1),node=$('.number-result');node.classList.add('spinning');let end=performance.now()+1450;const tick=now=>{node.querySelector('span').textContent=min+randomIndex(max-min+1);if(now<end)requestAnimationFrame(tick);else{node.classList.remove('spinning');node.querySelector('span').textContent=final;showNumberResult(final)}};requestAnimationFrame(tick)}
function showNumberResult(n){const panel=$('[data-view="number"] .result-panel');panel.className='result-panel show';panel.innerHTML=`<div class="result-label">这就是你的数字</div><div class="result-actions"><button class="keep">就它了</button><button class="again">再抽一次</button></div>`;panel.querySelector('.keep').onclick=()=>confirmResult(panel,'随机数字',n);panel.querySelector('.again').onclick=pickNumber}
function record(type,value){state.history.unshift({type,value,time:new Date().toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})});state.history=state.history.slice(0,12);save();renderHistory()}
function showToast(message){const toast=document.createElement('div');toast.className='toast';toast.textContent=message;document.body.append(toast);setTimeout(()=>toast.remove(),2400)}
function renderHistory(){const el=$('#history-list');el.innerHTML=state.history.length?state.history.map(x=>`<div class="history-item"><span>${x.type}</span><strong>${x.value}</strong><small>${x.time}</small></div>`).join(''):'<p class="tip">还没有决定记录。</p>'}
$$('[data-open]').forEach(b=>b.onclick=()=>showView(b.dataset.open));$('.back-button').onclick=()=>showView('home');$('#food-add').onclick=()=>add('food',$('#food-input'));$('#decide-add').onclick=()=>add('decide',$('#decide-input'));$('#food-restore').onclick=()=>{state.food=[...DEFAULT_FOOD];save();renderChips('food');showToast('默认食物已恢复')};$('#food-input').onkeydown=e=>{if(e.key==='Enter')add('food',e.target)};$('#decide-input').onkeydown=e=>{if(e.key==='Enter')add('decide',e.target)};$$('.decide-action').forEach(b=>b.onclick=()=>b.dataset.action==='number'?pickNumber():pick(b.dataset.action));$('.history-button').onclick=()=>{$('.history-drawer').hidden=false;renderHistory()};$('.close-history').onclick=()=>$('.history-drawer').hidden=true;renderChips('food');renderChips('decide');
