const DEFAULT_FOOD=['火锅','烧烤','炒饭','面','汉堡','炸鸡','日料','麻辣烫'];
const DEFAULT_DECIDE=['健身','看电影','打游戏','散步'];
const FOOD_ICONS=[['汉堡','🍔'],['炸鸡','🍗'],['日料','🍣'],['火锅','🍲'],['面','🍜'],['拉面','🍜'],['披萨','🍕'],['米饭','🍚'],['炒饭','🍚'],['烧烤','🍢'],['麻辣烫','🍲']];
const COPY=['今天老天爷让我吃 {r}，不是我想胖。','纠结结束，今天就 {r}。','不是我选了 {r}，是命运选的。','今天听天由命：{r}。','好了，不纠结了，{r}。'];
const state={food:JSON.parse(localStorage.getItem('pickone-food')||'null')||[...DEFAULT_FOOD],decide:JSON.parse(localStorage.getItem('pickone-decide')||'null')||[...DEFAULT_DECIDE],excluded:null,history:JSON.parse(localStorage.getItem('pickone-history')||'[]'),last:null};
const foodRuntime={raf:0,particleTimers:[],session:0};
const numberRuntime={raf:0,particleTimers:[],session:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function randomIndex(max){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max}
function save(){localStorage.setItem('pickone-food',JSON.stringify(state.food));localStorage.setItem('pickone-decide',JSON.stringify(state.decide));localStorage.setItem('pickone-history',JSON.stringify(state.history))}
function icon(name){const match=FOOD_ICONS.find(([key])=>name.includes(key));return match?match[1]:'🍽️'}
function safeVibrate(pattern){try{if('vibrate' in navigator)navigator.vibrate(pattern)}catch(e){}}
function resetSession(){const foodView=$('[data-view="food"]'),panel=foodView?.querySelector('.result-panel');foodRuntime.session+=1;if(foodRuntime.raf)cancelAnimationFrame(foodRuntime.raf);foodRuntime.raf=0;foodRuntime.particleTimers.splice(0).forEach(clearTimeout);foodView?.querySelectorAll('.result-particles,.result-glow').forEach(node=>node.remove());if(panel){panel.className='result-panel';panel.removeAttribute('style');panel.innerHTML=''}if(foodView){foodView.className='view decision-view food-state-idle';}state.last=null;state.excluded=null}
function resetToolState(name){const view=$(`[data-view="${name}"]`),panel=view?.querySelector('.result-panel'),runtime=name==='number'?numberRuntime:name==='decide'?foodRuntime:null;if(runtime){runtime.session+=1;if(runtime.raf)cancelAnimationFrame(runtime.raf);runtime.raf=0;runtime.particleTimers.splice(0).forEach(clearTimeout);view?.querySelectorAll('.result-particles,.result-glow').forEach(node=>node.remove())}if(panel){panel.className='result-panel';panel.removeAttribute('style');panel.innerHTML=''}view?.classList.remove('result-active','tool-state-spinning','tool-state-result');view?.classList.add('tool-state-idle');if(name==='number')view.querySelector('.number-result span').textContent='?';state.last=null;state.excluded=null}
function enterFoodPage(){resetSession();renderIdle()}
function renderIdle(){const foodView=$('[data-view="food"]');foodView.classList.add('active');updateFoodCount()}
function showView(name){if(name==='home'){resetSession();resetToolState('decide');resetToolState('number')}document.body.classList.remove('result-mode');document.body.classList.toggle('in-tool',name!=='home');$$('.view').forEach(v=>{v.classList.toggle('active',v.dataset.view===name);v.classList.remove('result-active')});$('.back-button').hidden=name==='home';state.excluded=null;if(name==='food')enterFoodPage();if(name==='decide'){resetToolState('decide');renderChips('decide')}if(name==='number')resetToolState('number')}
function renderChips(type){const el=$(`#${type}-options`);el.innerHTML='';state[type].forEach((item,i)=>{const chip=document.createElement('div');chip.className='chip';chip.innerHTML=`<span>${item}</span><button class="chip-remove" aria-label="删除${item}">×</button>`;chip.onclick=e=>{if(e.target.matches('button')){state[type].splice(i,1);save();renderChips(type);if(type==='food')updateFoodCount()}else chip.classList.toggle('off')};el.append(chip)});updateButtons()}
function updateFoodCount(){$('#food-count').textContent=state.food.length;$('#decide-count').textContent=state.decide.length;$('#number-range-label').textContent=`${$('#min-number').value}～${$('#max-number').value}`;updateButtons()}
function updateButtons(){const decide=$('[data-view="decide"] .decide-action');if(decide)decide.disabled=$$('#decide-options .chip:not(.off)').length<2}
function add(type,input){const value=input.value.trim();if(value&&!state[type].includes(value)){state[type].push(value);input.value='';save();renderChips(type);if(type==='food')updateFoodCount()}}
function playResultFeedback(panel,runtime){const layer=document.createElement('div');layer.className='result-particles';const count=window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:8;for(let i=0;i<count;i++){const p=document.createElement('i'),a=Math.PI*2*i/count+randomIndex(30)/100,d=24+randomIndex(22);p.style.setProperty('--x',`${Math.cos(a)*d}px`);p.style.setProperty('--y',`${Math.sin(a)*d}px`);p.style.setProperty('--size',`${3+randomIndex(3)}px`);p.style.setProperty('--delay',`${randomIndex(12)/100}s`);layer.append(p)}panel.append(layer);runtime.particleTimers.push(setTimeout(()=>layer.remove(),850))}
function makeParticles(panel){playResultFeedback(panel,panel.closest('[data-view="number"]')?numberRuntime:foodRuntime)}
function pick(type){const view=$(`[data-view="${type}"]`),panel=view.querySelector('.result-panel'),items=type==='food'?[...state.food]:[...document.querySelectorAll('#decide-options .chip:not(.off)')].map(x=>x.firstElementChild.textContent);const choices=items.filter(x=>x!==state.excluded);if(choices.length<2){showToast('至少需要 2 个有效选项');return}const final=choices[randomIndex(choices.length)];state.last={type,value:final};if(type==='food'){if(foodRuntime.raf)cancelAnimationFrame(foodRuntime.raf);foodRuntime.session+=1;view.classList.remove('food-state-idle','food-state-result');view.classList.add('food-state-spinning')}else{view.classList.remove('tool-state-idle','tool-state-result');view.classList.add('tool-state-spinning')}const session=foodRuntime.session;view.classList.add('result-active');panel.className='result-panel show';panel.innerHTML='<div class="result-glow"></div><div class="result-label">结果是</div><div class="result-value"></div><div class="result-actions"><button class="keep">就它了</button><button class="again">再来一次</button><button class="exclude">排除这个结果</button></div>';const node=panel.querySelector('.result-value'),end=performance.now()+1850;let slowed=false;safeVibrate(25);const tick=now=>{if(type==='food'&&session!==foodRuntime.session)return;if(now<end){if(!slowed&&now>end-550){slowed=true;safeVibrate([20,35,30])}const v=choices[randomIndex(choices.length)];node.textContent=(type==='food'?icon(v)+' ':'✨ ')+v;foodRuntime.raf=requestAnimationFrame(tick)}else{foodRuntime.raf=0;node.textContent=(type==='food'?icon(final)+' ':'✨ ')+final;if(type==='food'){view.classList.remove('food-state-spinning');view.classList.add('food-state-result')}else{view.classList.remove('tool-state-spinning');view.classList.add('tool-state-result')}panel.classList.add('locked');makeParticles(panel);safeVibrate([35,35,55])}};foodRuntime.raf=requestAnimationFrame(tick);panel.querySelector('.keep').onclick=()=>confirmResult(type,final);panel.querySelector('.again').onclick=()=>pick(type);panel.querySelector('.exclude').onclick=()=>{state.excluded=final;pick(type)}}
function pickNumber(){const min=Math.ceil(Number($('#min-number').value)),max=Math.floor(Number($('#max-number').value));if(!Number.isInteger(min)||!Number.isInteger(max)||min>=max){showToast('请输入有效的整数范围');return}const final=min+randomIndex(max-min+1),view=$('[data-view="number"]'),panel=view.querySelector('.result-panel');numberRuntime.session+=1;if(numberRuntime.raf)cancelAnimationFrame(numberRuntime.raf);numberRuntime.raf=0;numberRuntime.particleTimers.splice(0).forEach(clearTimeout);view.classList.remove('tool-state-idle','tool-state-result');view.classList.add('tool-state-spinning','result-active');panel.className='result-panel show';panel.innerHTML='<div class="result-glow"></div><div class="result-label">结果是</div><div class="result-value"></div><div class="result-actions"><button class="keep">就它了</button><button class="again">再来一次</button></div>';const node=panel.querySelector('.result-value'),session=numberRuntime.session,end=performance.now()+1900;let slowed=false;safeVibrate(25);const tick=now=>{if(session!==numberRuntime.session)return;if(now<end){if(!slowed&&now>end-550){slowed=true;safeVibrate([20,35,30])}node.textContent=min+randomIndex(max-min+1);numberRuntime.raf=requestAnimationFrame(tick)}else{numberRuntime.raf=0;node.textContent=final;state.last={type:'number',value:final};view.classList.remove('tool-state-spinning');view.classList.add('tool-state-result');panel.classList.add('locked');makeParticles(panel);safeVibrate([35,35,55])}};numberRuntime.raf=requestAnimationFrame(tick);panel.querySelector('.keep').onclick=()=>confirmResult('number',final);panel.querySelector('.again').onclick=pickNumber}
function confirmResult(type,value){record(type,value);$('#confirm-icon').textContent=type==='food'?icon(value):'✦';$('#confirm-value').textContent=value;$('#confirm-modal').hidden=false;safeVibrate([30,40,70])}
function finishConfirm(){if(state.last)showToast('已记下这次决定');$('#confirm-modal').hidden=true;showView('home')}
function record(type,value){state.history.unshift({type:type==='food'?'吃什么':type==='number'?'随机数字':'帮我决定',value,time:new Date().toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})});state.history=state.history.slice(0,12);save();renderHistory()}
function showToast(text){const t=document.createElement('div');t.className='toast';t.textContent=text;document.body.append(t);setTimeout(()=>t.remove(),2200)}
function renderHistory(){$('#history-list').innerHTML=state.history.length?state.history.map(x=>`<div class="history-item"><span>${x.type}</span><strong>${x.value}</strong><small>${x.time}</small></div>`).join(''):'<p>还没有决定记录。</p>'}
function drawPoster(){const c=$('#poster-canvas'),ctx=c.getContext('2d'),value=state.last?.value||'炸鸡',isFood=state.last?.type==='food';ctx.fillStyle='#f7f7f5';ctx.fillRect(0,0,c.width,c.height);const g=ctx.createRadialGradient(170,160,20,540,520,900);g.addColorStop(0,'#fff');g.addColorStop(1,'#f3d9cf');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#77777d';ctx.font='600 34px -apple-system, BlinkMacSystemFont, sans-serif';ctx.fillText('今天的决定',92,130);ctx.textAlign='center';ctx.font='150px "Apple Color Emoji","Segoe UI Emoji",sans-serif';ctx.fillText(isFood?icon(value):'✦',540,570);ctx.fillStyle='#1c1c1e';ctx.font='700 104px -apple-system, BlinkMacSystemFont, sans-serif';ctx.fillText(value,540,760);ctx.fillStyle='#5d5d63';ctx.font='36px -apple-system, BlinkMacSystemFont, sans-serif';const copy=COPY[state.copyIndex||0].replace('{r}',value),lines=copy.length>18?[copy.slice(0,18),copy.slice(18)]:[copy];lines.forEach((line,i)=>ctx.fillText(line,540,875+i*55));ctx.fillStyle='#77777d';ctx.font='28px -apple-system, BlinkMacSystemFont, sans-serif';ctx.fillText('Pick one · 今天纠结什么？',540,1320);ctx.textAlign='start'}
function openPoster(){state.copyIndex=randomIndex(COPY.length);drawPoster();$('#poster-modal').hidden=false}
function savePoster(){const a=document.createElement('a');a.download='pick-one-'+(state.last?.value||'decision')+'.png';a.href=$('#poster-canvas').toDataURL('image/png');a.click()}
async function sharePoster(){if(!navigator.share){showToast('当前浏览器不支持直接分享');return}const blob=await new Promise(r=>$('#poster-canvas').toBlob(r,'image/png'));const file=new File([blob],'pick-one.png',{type:'image/png'});try{await navigator.share({title:'今天的决定',text:`今天就${state.last?.value||'它了'}`,files:[file]})}catch(e){if(e.name!=='AbortError')showToast('分享暂时不可用')}}
$$('[data-open]').forEach(b=>b.onclick=()=>showView(b.dataset.open));$('.back-button').onclick=()=>showView('home');$('#open-food-sheet').onclick=()=>{$('#food-sheet').hidden=false;$('#sheet-backdrop').hidden=false;renderChips('food')};function closeSheet(){$$('.bottom-sheet').forEach(s=>s.hidden=true);$('#sheet-backdrop').hidden=true}$('#close-food-sheet').onclick=closeSheet;$('.close-tool-sheet').forEach(b=>b.onclick=closeSheet);$('#sheet-backdrop').onclick=closeSheet;$('#food-add').onclick=()=>add('food',$('#food-input'));$('#food-input').onkeydown=e=>{if(e.key==='Enter')add('food',e.target)};$('#food-restore').onclick=()=>{state.food=[...DEFAULT_FOOD];save();renderChips('food');updateFoodCount();showToast('默认食物已恢复')};$('#open-decide-sheet').onclick=()=>{$('#decide-sheet').hidden=false;$('#sheet-backdrop').hidden=false;renderChips('decide')};$('#decide-add').onclick=()=>add('decide',$('#decide-input'));$('#decide-input').onkeydown=e=>{if(e.key==='Enter')add('decide',e.target)};$('#open-number-sheet').onclick=()=>{$('#number-sheet').hidden=false;$('#sheet-backdrop').hidden=false};$('#save-number-range').onclick=()=>{const min=Number($('#min-number').value),max=Number($('#max-number').value);if(!Number.isInteger(min)||!Number.isInteger(max)||min>=max){showToast('请输入有效的整数范围');return}updateFoodCount();closeSheet()};$$('.decide-action').forEach(b=>b.onclick=()=>b.dataset.action==='number'?pickNumber():pick(b.dataset.action));$('#finish-confirm').onclick=finishConfirm;$('#home-confirm').onclick=()=>{$('#confirm-modal').hidden=true;showView('home')};$('#make-poster').onclick=openPoster;$('#close-poster').onclick=()=>$('#poster-modal').hidden=true;$('#save-poster').onclick=savePoster;$('#new-copy').onclick=()=>{state.copyIndex=randomIndex(COPY.length);drawPoster()};$('#share-poster').onclick=sharePoster;if(!navigator.share)$('#share-poster').hidden=true;$('.history-button').onclick=()=>{$('.history-drawer').hidden=false;renderHistory()};$('.close-history').onclick=()=>$('.history-drawer').hidden=true;updateFoodCount();renderChips('decide');
